apiVersion: v1
kind: ReplicationController
metadata:
  name: hello-k8s-rc-v1.0
spec:
  replicas: 2
  selector:
    app: hello-k8s
    version: v1.0
  template:
    metadata:
      name: hello-k8s
      labels:
        app: hello-k8s
        version: v1.0
    spec:
      containers:
      - name: hello-k8s
        image: registry.cn-hangzhou.aliyuncs.com/xinchen0618/hello-k8s:latest
        ports:
        - containerPort: 80
        env:
        - name: ENV
          value: dev
